// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
//  Created by Sam Deane on 23/07/2026.
//  Copyright © 2026 Elegant Chaos Limited. All rights reserved.
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

import Foundation

/// Copies canonical shared rules into the Codex runtime rules directory.
final class RulesPublicTool {
  /// Header prepended to generated runtime copies.
  static let managedHeader =
    "# Managed by ~/.local/share/agents. Do not edit this file manually.\n\n"

  /// Filesystem implementation used for rule discovery and updates.
  private let fileManager: FileManager

  /// Directory containing canonical shared rules.
  private let sharedRulesDirectory: URL

  /// Directory containing the runtime copies consumed by Codex.
  private let runtimeRulesDirectory: URL

  /// Creates the command-line tool using repository and Codex environment settings.
  convenience init() throws {
    let fileManager = FileManager.default
    let repoRoot = try RepoRootLocator.locateRepoRoot(
      environment: ProcessInfo.processInfo.environment,
      currentDirectoryPath: fileManager.currentDirectoryPath,
      fileExistsAtPath: fileManager.fileExists(atPath:)
    )
    let codexHome = URL(
      fileURLWithPath: ProcessInfo.processInfo.environment["CODEX_HOME"]
        ?? fileManager.homeDirectoryForCurrentUser.appendingPathComponent(".codex").path
    )
    self.init(
      repoRoot: repoRoot,
      runtimeRulesDirectory: codexHome.appendingPathComponent("rules"),
      fileManager: fileManager
    )
  }

  /// Creates a tool with explicit paths for testing or embedding.
  init(
    repoRoot: URL,
    runtimeRulesDirectory: URL,
    fileManager: FileManager = .default
  ) {
    self.fileManager = fileManager
    self.sharedRulesDirectory = repoRoot.appendingPathComponent("codex/rules")
    self.runtimeRulesDirectory = runtimeRulesDirectory
  }

  /// Reports drift between shared sources and runtime copies without changing files.
  func inspect() throws -> RulesSyncReport {
    try report(synchronizing: false)
  }

  /// Overwrites runtime copies with canonical shared content.
  func synchronize() throws -> RulesSyncReport {
    try fileManager.createDirectory(
      at: runtimeRulesDirectory,
      withIntermediateDirectories: true
    )
    return try report(synchronizing: true)
  }

  /// Inspects every rules file and optionally writes canonical runtime copies.
  private func report(synchronizing: Bool) throws -> RulesSyncReport {
    let sharedFiles = try ruleFiles(in: sharedRulesDirectory)
    guard sharedFiles["default.rules"] == nil else {
      throw ToolError(
        "codex/rules/default.rules must not be stored in the shared repository; keep it runtime-only."
      )
    }
    let runtimeFiles = try ruleFiles(in: runtimeRulesDirectory)
    let names = Set(sharedFiles.keys).union(runtimeFiles.keys)

    let entries = try names.sorted().map { name in
      try inspect(
        name: name,
        sharedFile: sharedFiles[name],
        runtimeFile: runtimeFiles[name],
        synchronizing: synchronizing
      )
    }
    return RulesSyncReport(entries: entries)
  }

  /// Inspects and optionally synchronizes one rules filename.
  private func inspect(
    name: String,
    sharedFile: URL?,
    runtimeFile: URL?,
    synchronizing: Bool
  ) throws -> RulesSyncEntry {
    guard let sharedFile else {
      return RulesSyncEntry(name: name, status: .runtimeOnly)
    }

    let sharedData = try Data(contentsOf: sharedFile)
    let runtimeCopyData = try renderedRuntimeCopy(from: sharedData, named: name)
    guard let runtimeFile, let runtimeData = try readDataIfAvailable(from: runtimeFile) else {
      if synchronizing {
        try writeRuntimeCopy(runtimeCopyData, named: name)
        return RulesSyncEntry(name: name, status: .copied)
      }
      return RulesSyncEntry(name: name, status: .drifted)
    }

    let symlink = isSymlink(runtimeFile)
    let contentsMatch = runtimeCopyData == runtimeData
    guard synchronizing else {
      if symlink {
        return RulesSyncEntry(name: name, status: .symlink)
      }
      return RulesSyncEntry(name: name, status: contentsMatch ? .unchanged : .drifted)
    }

    try writeRuntimeCopy(runtimeCopyData, named: name)
    let status: RulesSyncEntry.Status
    if symlink {
      status = .replacedSymlink
    } else if contentsMatch {
      status = .unchanged
    } else {
      status = .overwritten
    }
    return RulesSyncEntry(name: name, status: status)
  }

  /// Prepends the generated-file warning to canonical UTF-8 rule content.
  private func renderedRuntimeCopy(from sharedData: Data, named name: String) throws -> Data {
    guard let sharedRules = String(data: sharedData, encoding: .utf8) else {
      throw ToolError("Shared rules file is not valid UTF-8: \(name)")
    }
    return Data((Self.managedHeader + sharedRules).utf8)
  }

  /// Writes a regular runtime copy, removing any existing file or symlink first.
  private func writeRuntimeCopy(_ data: Data, named name: String) throws {
    let runtimeFile = runtimeRulesDirectory.appendingPathComponent(name)
    if pathExistsIncludingBrokenSymlink(runtimeFile) {
      try fileManager.removeItem(at: runtimeFile)
    }
    try data.write(to: runtimeFile, options: .atomic)
  }

  /// Discovers top-level `.rules` files, including symbolic links.
  private func ruleFiles(in directory: URL) throws -> [String: URL] {
    guard fileManager.fileExists(atPath: directory.path) else {
      return [:]
    }

    let files = try fileManager.contentsOfDirectory(
      at: directory,
      includingPropertiesForKeys: nil,
      options: [.skipsHiddenFiles]
    )
    return Dictionary(
      uniqueKeysWithValues:
        files
        .filter { $0.pathExtension == "rules" }
        .map { ($0.lastPathComponent, $0) }
    )
  }

  /// Reads a file when the path resolves, returning nil for broken symlinks.
  private func readDataIfAvailable(from url: URL) throws -> Data? {
    do {
      return try Data(contentsOf: url)
    } catch CocoaError.fileReadNoSuchFile {
      return nil
    }
  }

  /// Returns true when a path is a symbolic link.
  private func isSymlink(_ url: URL) -> Bool {
    var info = stat()
    guard lstat(url.path, &info) == 0 else { return false }
    return (info.st_mode & S_IFMT) == S_IFLNK
  }

  /// Returns true when a path exists, including a broken symbolic link.
  private func pathExistsIncludingBrokenSymlink(_ url: URL) -> Bool {
    var info = stat()
    return lstat(url.path, &info) == 0
  }
}
